#+TITLE: Config
#+AUTHOR: Mjolnir
* General Settings
**  Setting my Font for Doom Emacs, and making it pretty

#+begin_src emacs-lisp
  (setq doom-font (font-spec :family "FantasqueSansMono Nerd Font" :size 33))
  (custom-set-faces! '(mode-line-active :inherit mode-line))
  (setq doom-theme 'doom-gruvbox-light)
  (setq display-line-numbers-type 'relative)
  (setq edebug-print-length 'nil)
  (setq global-emojify-mode 'nil)
#+end_src

**  Ensure that Emacsql-sqlite is easy to find.

#+begin_src emacs-lisp :tangle packages.el
(package! emacsql-sqlite :built-in 'prefer)
#+end_src
**  Makes Richard Stallman visit my Emacs
#+begin_src emacs-lisp
(setq fancy-splash-image "~/Pictures/emacs.png")
#+end_src

**  Other small improvements
#+begin_src emacs-lisp
(setq auto-save-default t)
(setq which-key-idle-delay 0.25)
(display-time-mode 1)
#+end_src

**  Spelling in Emacs
#+begin_src emacs-lisp
;;(setq ispell-dictionary "en-custom")
;;(setq ispell-personal-dictionary (expand-file-name ".ispell_personal" doom-private-dir))
#+end_src

**  General LSP stuff
#+begin_src emacs-lisp
(after! lsp-ui
  (setq lsp-ui-doc-enable 1)
  (setq! lsp-ui-doc-delay 0)
  (setq lsp-ui-doc-show-with-cursor t)
  (setq lsp-ui-doc-max-width 200)
  (setq lsp-ui-doc-max-height 50)
  (setq lsp-ui-doc-use-webkit nil)
  (setq lsp-ui-doc-border 'unspecified)
  (setq! lsp-ui-peek-enable t))
(after! lsp
  (setq lsp-enable-symbol-highlighting nil))

#+end_src

**  Adding info-colors to improving reaidngs:
Tell doom the package exists
#+begin_src emacs-lisp :tangle packages.el
(package! info-colors :pin "47ee73cc19b1049eef32c9f3e264ea7ef2aaf8a5")
#+end_src

Actually using the package
#+begin_src emacs-lisp
(use-package! info-colors
  :hook (Info-selection . info-colors-fontify-node))
#+end_src
**  Making Infos no longer a popup
#+begin_src emacs-lisp
(set-popup-rules! '(("^\\*info\\*$" ; Info buffers
                     :ignore t)))
#+end_src
**  Keycast for showing off Emacs
Installing Keycast
#+begin_src emacs-lisp :tangle packages.el
(package! keycast :pin "04ba7519f34421c235bac458f0192c130f732f12")
#+end_src
Making Keycast work in the modeline:
#+begin_src emacs-lisp
(use-package! keycast
  :commands keycast-mode
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" mode-line-keycast " ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (remove '("" mode-line-keycast " ") global-mode-string))))
  (custom-set-faces!
    '(keycast-command :inherit doom-modeline-debug
                      :height 0.9)
    '(keycast-key :inherit custom-modified
                  :height 1.1
                  :weight)))
#+end_src

**  Modeline tweak to not show utf-8
#+begin_src emacs-lisp
(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8, so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (unless (and (memq (plist-get (coding-system-plist buffer-file-coding-system) :category)
                                 '(coding-category-undecided coding-category-utf-8))
                           (not (memq (coding-system-eol-type buffer-file-coding-system) '(1 2))))
                t)))

(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)

#+end_src

* Org-mode stuffs
Setting org directory
#+begin_src emacs-lisp
(setq org-directory "~/Org/")
#+end_src

Making small changes to org that make org more usable for notes and literate development
#+begin_src emacs-lisp
(after! org
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 2.0))
  (setq org-src-fontify-natively t
        org-ellipsis " ▾ "
        org-startup-folded t
        org-hide-emphasis-markers t))
 ;; (add-hook 'org-mode-hook 'turn-on-flyspell)
#+end_src

Making org-super-agenda usable once i install this on wsl(eventually)
#+begin_src emacs-lisp
;;(use-package! org-super-agenda
 ;; :after org-agenda
 ;; :init
  ;;setq org-super-agenda-groups '((:name "Today"
 ;;                                         :time-grid t
   ;;                                       :scheduled today)
    ;;                              (:name "Due today"
     ;;                                     :deadline today)
      ;;                            (:name "Important"
        ;;                                  :priority "A")
           ;;                       (:name "overdue"
         ;;                                 :deadline past)
       ;;                           (:name "Due soon"
     ;;                                    :deadline future)
   ;;                               (:name "Big Outcomes"
         ;;                                :tag "bo")))
 ;; :config
#+end_src

making org bullets look silly
#+begin_src emacs-lisp
(after! org-superstar
  (setq org-superstar-headline-bullets-list'("🍺" "📀" "📠" "👉" "🔭" "🔮" "☄️") org-superstar-prettify-item-bullets t))

#+end_src

* Rust stuff
setting up rust lsp stuffs
#+begin_src emacs-lisp
(after! rustic
  (setq rustic-lsp-server 'rust-analyzer))
#+end_src

* Note-Taking Stuff
As an opening note here, most of this may fall under [[Org mode stuffs][Org mode]], though I feel it has parts that make it distinct enough.
** Reading in Emacs
This will allow me to open a given book, *.epub*, or *.pdf* file and comfortably read it from the inside of Emacs. This should concert neatly with this section of the config as well, as maybe being a help for writing code.

#+begin_src emacs-lisp :tangle packages.el
(package! nov :pin "b3c7cc28e95fe25ce7b443e5f49e2e45360944a3")
#+end_src

Stealing a chunk of tec's config for nov, to make it better to use.

#+begin_src emacs-lisp
(use-package! nov
  :mode ("\\.epub\\'" . nov-mode)
  :config
  (map! :map nov-mode-map
        :n "RET" #'nov-scroll-up)

  (defun doom-modeline-segment--nov-info ()
    (concat
     " "
     (propertize
      (cdr (assoc 'creator nov-metadata))
      'face 'doom-modeline-project-parent-dir)
     " "
     (cdr (assoc 'title nov-metadata))
     " "
     (propertize
      (format "%d/%d"
              (1+ nov-documents-index)
              (length nov-documents))
      'face 'doom-modeline-info)))

  (advice-add 'nov-render-title :override #'ignore)

  (defun +nov-mode-setup ()
    (face-remap-add-relative 'variable-pitch
                             :family "Merriweather"
                             :height 1.4
                             :width 'semi-expanded)
    (face-remap-add-relative 'default :height 1.3)
    (setq-local line-spacing 0.2
                next-screen-context-lines 4
                shr-use-colors nil)
    (require 'visual-fill-column nil t)
    (setq-local visual-fill-column-center-text t
                visual-fill-column-width 81
                nov-text-width 80)
    (visual-fill-column-mode 1)
    (hl-line-mode -1)

    (add-to-list '+lookup-definition-functions #'+lookup/dictionary-definition)

    (setq-local mode-line-format
                `((:eval
                   (doom-modeline-segment--workspace-name))
                  (:eval
                   (doom-modeline-segment--window-number))
                  (:eval
                   (doom-modeline-segment--nov-info))
                  ,(propertize
                    " %P "
                    'face 'doom-modeline-buffer-minor-mode)
                  ,(propertize
                    " "
                    'face (if (doom-modeline--active) 'mode-line 'mode-line-inactive)
                    'display `((space
                                :align-to
                                (- (+ right right-fringe right-margin)
                                   ,(* (let ((width (doom-modeline--font-width)))
                                         (or (and (= width 1) 1)
                                             (/ width (frame-char-width) 1.0)))
                                       (string-width
                                        (format-mode-line (cons "" '(:eval (doom-modeline-segment--major-mode))))))))))
                  (:eval (doom-modeline-segment--major-mode)))))

  (add-hook 'nov-mode-hook #'+nov-mode-setup))

#+end_src
